version: "3.1"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    restart: always
    ports:
      - 3001:3001
    networks:
      - mern
    volumes: 
      - ./server:/app
    depends_on:
      - mongo
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
    networks:
      - mern
    depends_on:
      - server
  mongo:
    image: mongo
    container_name: db
    ports: 
      - "27017:27017"
    restart: always
    networks: 
      - mern
    volumes: 
      - ./mongodb:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongoExpress
    restart: always
    networks: 
      - mern
    ports:
      - "8081:8081"
volumes: 
    mongodb:
networks:
  mern:
    driver: bridge
